BeginVegan/BV-Backend

src/main/java/com/beginvegan/dto/BookmarkDTO.java, src/main/java/com/beginvegan/dto/PointDTO.java, src/main/java/com/beginvegan/dto/ReservationDTO.java, src/main/java/com/beginvegan/dto/ReviewDTO.java, src/main/java/com/beginvegan/repository/MemberRepository.java
MemberRepository 인터페이스 메소드 작성했습니다.
insertMember(memberInfo:MemberDTO):void
updateMember(memberEmail:String):void
deleteMember(memberEmail:String):void
selectMemberByMemberEmail(memberEmail:String):void
insertPoint(poinrtInfo:pointDTO):void
selectAllPointByMemberEmail(userEmail:String):List<PointDTO>
insertBookmark(restaurantNo:int)void
deleteBookmark(restaurantNo:int)void
selectAllBookmarkByMemberEmail:String):List<BookmarkDTO>
=> MemberRepository 인터페이스 메소드 작성

src/main/java/com/beginvegan/controller/RestaurantController.java, src/main/java/com/beginvegan/repository/RestaurantRepository.java, src/main/java/com/beginvegan/repository/RestaurantRepositoryMariaDB.java, src/main/java/com/beginvegan/service/RestaurantService.java, src/main/resources/mapper/RestaurantMapper.xml
=> 전체 레스토랑 조회 구현

src/main/java/com/beginvegan/repository/MemberRepositoryMariaDB.java, src/main/resources/mapper/MemberMapper.xml
요구사항에 명시된 기능 1차 구현
- MemberRepositoryMariaDB 메소드 작성
- MemberMapper 쿼리 작성
=> feat: MemberRepositoryMariaDB 및 MemberMapper 기능, 쿼리 작성

src/main/java/com/beginvegan/dto/PointDTO.java, src/main/java/com/beginvegan/repository/MemberRepositoryMariaDB.java, src/main/resources/mapper/MemberMapper.xml, src/test/com/beginvegan/repository/MemberRepositoryMariaDBTest.java
MemberRepositoryMariaDB JUnitTEST 완료!
=> feat: MemberRepositoryMariaDB JUnitTEST 완료

src/main/java/com/beginvegan/service/MemberService.java, src/main/java/com/beginvegan/util/FileIO.java, src/main/java/com/beginvegan/util/KakaoAPI.java, src/main/java/com/beginvegan/util/KakaoLogin.java
MemberService 구현 및 KakaoAPI 유틸 추가했습니다.
=> feat: MemberService 구현 및 KakaoAPI 유틸 추가

src/main/java/com/beginvegan/controller/MyPageController.java, src/main/java/com/beginvegan/dto/ReviewDTO.java, src/main/java/com/beginvegan/repository/MemberRepository.java, src/main/java/com/beginvegan/repository/ReviewRepository.java, src/main/java/com/beginvegan/repository/ReviewRepositoryMariaDB.java, src/main/java/com/beginvegan/service/MyPageService.java, src/main/resources/mapper/ReviewMapper.xml, src/test/com/beginvegan/repository/ReviewRepositoryMariaDBTest.java
=> feat: controller service repository 치훈 할당분 완성 초안

pom.xml, src/main/java/com/beginvegan/repository/MemberRepository.java, src/main/java/com/beginvegan/repository/MemberRepositoryMariaDB.java, src/test/com/beginvegan/repository/MemberRepositoryMariaDBTest.java
=> fix: MemberRepository 테스트 관련 수정

src/main/java/com/beginvegan/util/TimeUtil.java
- clock을 사용한 시간설정
- 시간변환 메서드 생성(string -> localTime)
=> 시간관련 유틸 클래스 생성

src/main/java/com/beginvegan/controller/ReservationController.java, src/main/java/com/beginvegan/dto/ReservationDTO.java, src/main/java/com/beginvegan/repository/ReservationRepository.java, src/main/java/com/beginvegan/repository/ReservationRepositoryMariaDB.java, src/main/java/com/beginvegan/service/ReservationService.java, src/main/resources/mapper/ReservationMapper.xml
- 예약 생성, 조회, 삭제, 수정 api 구현
- ReservationRepository 구현체를 mybatis를 통해 구현
=> 예약 관련 기본 crud api 구현

pom.xml, src/main/java/com/beginvegan/service/MemberService.java, src/main/java/com/beginvegan/util/GetGoogleAccount.java, src/main/java/com/beginvegan/util/GetKakaoAccount.java, src/test/com/beginvegan/service/MemberServiceTest.java
- google 로그인 기능 추가
- 테스트 코드 Session Moack 객체 수정
- 테스트 코드 작성 테스트 완료
=> feat: Google 로그인 추가 및 테스트 코드 작성

src/main/java/com/beginvegan/controller/ReservationController.java, src/main/java/com/beginvegan/dto/ReservationDTO.java, src/main/java/com/beginvegan/dto/ReservationMenuDTO.java, src/main/java/com/beginvegan/repository/ReservationRepositoryMariaDB.java, src/main/resources/mapper/ReservationMapper.xml
- Reservation등록시 autoIncrement reservationNo 가져와서 등록
- resultMap을 통한 1:N(Reservation:ReservationMenu) 관계 처리
=> Reservation Api 수정

pom.xml, src/main/java/com/beginvegan/controller/ReservationController.java, src/main/java/com/beginvegan/dto/PointDTO.java, src/main/java/com/beginvegan/dto/ReservationDTO.java, src/main/java/com/beginvegan/dto/ReservationMenuDTO.java, src/main/java/com/beginvegan/repository/MemberRepositoryMariaDB.java, src/main/java/com/beginvegan/repository/ReservationRepositoryMariaDB.java, src/main/java/com/beginvegan/util/TimeUtil.java, src/main/resources/logback-spring.xml, src/main/resources/mapper/ReservationMapper.xml, src/main/resources/spy.properties, src/test/com/beginvegan/repository/MemberRepositoryMariaDBTest.java
로깅 라이브러리 p6psy로 변경 완료, 기존 log4jdvc 제거
PointDTO 날짜, 시간 자료형 변경 및 테스트 코드 변경 및 테스트 통과
TimeUtil 메소드 몇개 추가
=> feat: 로깅 라이브러리 변경, 및 PointDTO 변경

src/main/java/com/beginvegan/controller/ReservationController.java, src/main/java/com/beginvegan/dto/ReservationDTO.java, src/main/java/com/beginvegan/repository/ReservationRepository.java, src/main/java/com/beginvegan/repository/ReservationRepositoryMariaDB.java, src/main/resources/mapper/ReservationMapper.xml
- Reservation 테이블의 다음 생성 넘버(autoIncrement) 가져오는 메서드 구현
- Controller에서 RequestBody를 통해 reservationDTO를 넘겨받도록 수정(기존에는 Map으로 넘겨받았음)
- 예약 등록, 수정, 삭제 시 예약하는 메뉴까지 등록되고 수정되도록 변경
=> 예약 api 로직 추가 및 수정

src/main/java/com/beginvegan/controller/ReservationController.java, src/main/java/com/beginvegan/repository/ReservationRepositoryMariaDB.java
=> 예약 등록, 수정 시 예약의 메뉴까지 적용되도록 변경

src/main/java/com/beginvegan/controller/MemberController.java
=> fix: MemberController 맵핑 중복 수정

src/main/java/com/beginvegan/controller/MemberController.java, src/main/java/com/beginvegan/controller/MyPageController.java, src/test/com/beginvegan/controller/MemberControllerTest.java
MemberController TEST 완료
주석 바로 다음 머지에서 추가 예정
=> feat: MemberController TEST 완료

src/main/java/com/beginvegan/controller/MemberController.java
=> sessionCheck용 컨트롤러 추가

src/main/java/com/beginvegan/dto/RestaurantDTO.java, src/main/java/com/beginvegan/repository/RestaurantRepository.java, src/main/java/com/beginvegan/repository/RestaurantRepositoryMariaDB.java, src/main/resources/mapper/RestaurantMapper.xml, src/test/com/beginvegan/repository/RestaurantRepositoryMariaDBTest.java
* 테스트코드 추가
* ResultMap으로 한번에 Restaurant과 Menu 정보 얻어오기
* Repository에 log 추가
* 시간 형식을 LocalTime형으로 변경
=> feat: 테스트코드 추가, ResultMap으로 Restaurant과 Menu 정보 한번에 얻어오기

pom.xml, src/main/java/com/beginvegan/config/S3Config.java, src/main/java/com/beginvegan/controller/RestaurantController.java, src/main/java/com/beginvegan/repository/RestaurantRepository.java, src/main/java/com/beginvegan/repository/RestaurantRepositoryMariaDB.java, src/main/java/com/beginvegan/service/RestaurantService.java, src/main/java/com/beginvegan/service/S3Service.java, src/main/resources/mapper/RestaurantMapper.xml
- aws s3 설정 및 Service 구현
- s3를 통한 이미지 서비스(single, multi), 삭제, 가져오기(폴더내의 전체 이미지)
=> feat: aws를 통한 image파일 업로드 구현

src/main/java/com/beginvegan/controller/MyPageController.java, src/main/java/com/beginvegan/controller/ReservationController.java, src/main/java/com/beginvegan/dto/ReviewDTO.java, src/main/java/com/beginvegan/service/MyPageService.java
=> feat(리뷰): 리뷰 작성기능 추가

src/main/java/com/beginvegan/controller/ReservationController.java, src/main/java/com/beginvegan/repository/ReservationRepository.java, src/main/java/com/beginvegan/repository/ReservationRepositoryMariaDB.java, src/main/java/com/beginvegan/service/ReservationService.java, src/main/java/com/beginvegan/service/TossService.java, src/main/resources/mapper/ReservationMapper.xml
- PaymentService가 추가됨에 따라 ReservationService의 로직 변경
- 예약이 삭제되면 결제가 삭제되고 iamport 결제취소
- 예약이 수정되면 결제가 삭제되고 iamport 결제취소
=> PaymentService에 따른 ReservationService 수정
